---
# tasks file for jenkins
- name: Creando yaml de despliegue 
  copy:
    dest: "jenkins.yaml"
    content: |
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: jenkins
       labels:
         app: jenkins
     spec:
       replicas: 1
       selector:
         matchLabels:
           app: jenkins
       template:
         metadata:
           labels:
             app: jenkins
         spec:
            containers:
            - name: jenkins
              image: jenkins/jenkins:2.289.2-lts-centos7     
              ports:
              - containerPort: 8080
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: jenkins-service
   namespace: jenkins-routed
 spec:
   selector:
     app: jenkins-routed
 ports:
 - name: http
   protocol: TCP
   port: 80 # puerto en el que escucha el servicio
   targetPort: 8080 # puerto en el que escucha el contenedor
  become: yes 
- name: Desplegando jenkins en kubernetes
  shell: |
    kubectl apply -f jenkins.yaml --validate=false
  become: yes
