---
# tasks file for jenkins
- name: Creando yaml de despliegue 
  copy:
    dest: "jenkins.yaml"
    content: |
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: jenkins
       labels:
         app: jenkins
     spec:
       replicas: 1
       selector:
         matchLabels:
           app: jenkins
       template:
         metadata:
           labels:
             app: jenkins
         spec:
            containers:
            - name: jenkins
            image: jenkins/jenkins:2.289.2-lts-centos7     
            ports:
            - containerPort: 8080
  become: yes 
