---
# tasks file for conf-workers
- name: Abrir cortafuegos para sdn
  shell: |
    firewall-cmd --permanent --add-port=8285/udp
    firewall-cmd --permanent --add-port=8472/udp
    firewall-cmd --reload
  become: yes
- name: Abrir cortafuegos para Master
  shell: |
    firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
    firewall-cmd --reload
  become: yes
- name: kubeadm
  shell: |
    kubeadm join 10.0.1.10:6443 --token n6998y.kf523uhd01szsibf --discovery-token-ca-cert-hash sha256:1db0a6db85ada3f1482fd459fc305d53a01b7a1b908ba488133c11d6d0ee96bd
  become: yes

